name = "ddns-asus-cloudflared"
main = "src/worker.js"
compatibility_date = "2024-08-22"
workers_dev = true
node_compat = true
# tail_consumers = [{service = "workers-logs"}] # need paid plan

kv_namespaces = [
	{ binding = "DDNS_STORE", id = "be83a5b1c6c942299f0b1e1d9c8cd561" }
]

[vars]
ROUTER_MAC = ""
ROUTER_WPS = ""
DDNS_DOMAIN = ".asuscomm.com"

CLOUDFLARE_API_TOKEN = ""
CLOUDFLARE_ACCOUNT_ID = ""
CLOUDFLARE_CONNECTOR_ID = ""

NOTIFY_TOKEN = ""

[env.dev.triggers]
crons = ["2 * * * *"]


[observability]
enabled = true
