name = "ddns-asus-cloudflared"
main = "src/worker.js"
compatibility_date = "2024-08-22"
workers_dev = true
node_compat = true

kv_namespaces = [
	{ binding = "DDNS_STORE", id = "be83a5b1c6c942299f0b1e1d9c8cd561" }
]

[vars]
ROUTER_MAC = ""
ROUTER_WPS = ""
DDNS_DOMAIN = ".asuscomm.com"

CLOUDFLARE_API_TOKEN = ""
CLOUDFLARE_ACCOUNT_ID = ""
CLOUDFLARE_TUNNEL_ID = ""

NOTIFY_TOKEN = ""

# Workers Logs billing will begin on November 1, 2024.
[observability]
enabled = true

# Dev Settings
[env.dev.triggers]
crons = ["2 * * * *"]
